example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import post_wishlist, show_json_by_id, show_xml_by_id, show_wishlist, show_wishlist_ajax, show_xml, show_json, register, login_user, logout_user

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('ajax/submit', post_wishlist, name='post_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
import datetime
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.core import serializers
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

from wishlist.models import BarangWishlist

# Referensi Lab 5:
# 1. https://api.jquery.com/id-selector/
# 2. https://stackoverflow.com/questions/1960240/jquery-ajax-submit-form

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Emir Shamsuddin Fadhlurrahman',
        'last_login': request.COOKIES['last_login'],
    }
    
    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    context = {
        'nama': 'Emir Shamsuddin Fadhlurrahman',
        'last_login': request.COOKIES['last_login'],
    }
    
    return render(request, "wishlist_ajax.html", context)

@login_required(login_url='/wishlist/login/')
def post_wishlist(request):
    if request.method == 'POST':
        nama_barang = request.POST.get('nama_barang');
        harga_barang = request.POST.get('harga_barang');
        deskripsi = request.POST.get('deskripsi');
        
        BarangWishlist.objects.create(nama_barang=nama_barang, harga_barang=harga_barang, deskripsi=deskripsi);
    
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize('json', data), content_type='application/json')

def show_xml(request):
    data = BarangWishlist.objects.all()
    
    return HttpResponse(serializers.serialize('xml', data), content_type='application/xml')

def show_json(request):
    data = BarangWishlist.objects.all()
    
    return HttpResponse(serializers.serialize('json', data), content_type='application/json')

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    
    return HttpResponse(serializers.serialize('json', data), content_type='application/json')

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    
    return HttpResponse(serializers.serialize('xml', data), content_type='application/xml')

def register(request):
    form = UserCreationForm()
    
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = { 'form': form }
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse('wishlist:show_wishlist'))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar navbar-expand-lg bg-success">
    <div class="container-fluid">
        <a class="navbar-brand text-light" href=""><b>Wish List</b></a>
        <span class="text-light">{{nama}}</span>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <button><a href="{% url 'wishlist:logout' %}">Logout</a></button>
                </li>
            </ul>
        </div>
    </div>
</nav>

<h5 class="mt-2">Nama: </h5>
<p>{{nama}}</p>

<hr>

<h2 class="text-center">List Barang</h2>
<table class="table">
    <thead>
        <tr>
            <th>Nama Barang</th>
            <th>Harga Barang</th>
            <th>Deskripsi</th>
        </tr>
    </thead>
    <tbody>
        {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
        {% for barang in list_barang %}
            <tr>
                <th>{{barang.nama_barang}}</th>
                <th>{{barang.harga_barang}}</th>
                <th>{{barang.deskripsi}}</th>
            </tr>
        {% endfor %}
    </tbody>
</table>

<h5>Sesi terakhir login: {{ last_login }}</h5>

<button><a href="{% url 'wishlist:logout' %}">Logout</a></button>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block meta %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        $.get("http://127.0.0.1:8000/wishlist/ajax/submit", function(data) {
            let tableBody = $('#table-body');
            tableBody.empty();
            
            data.forEach(function(element) {
                tableBody.append(`<tr><th>${element.fields.nama_barang}</th><th>${element.fields.harga_barang}</th><th>${element.fields.deskripsi}</th></tr>`);
            });
        });
        
        let form = $('#form');
        form.submit(function(e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: form.attr('action'),
                data: form.serialize(),
                success: function(data) {
                    let tableBody = $('#table-body');
                    tableBody.empty();
                    
                    data.forEach(function(element) {
                        tableBody.append(`<tr><th>${element.fields.nama_barang}</th><th>${element.fields.harga_barang}</th><th>${element.fields.deskripsi}</th></tr>`);
                    });
                },
            });
        });
    });
</script>
{% endblock meta %}

{% block content %}
<nav class="navbar navbar-expand-lg bg-success">
    <div class="container-fluid">
        <a class="navbar-brand text-light" href=""><b>Wish List</b></a>
        <span class="text-light">{{nama}}</span>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <button><a href="{% url 'wishlist:logout' %}">Logout</a></button>
                </li>
            </ul>
        </div>
    </div>
</nav>

<h5 class="mt-2">Nama: </h5>
<p>{{nama}}</p>

<hr>

<h2 class="text-center">List Barang</h2>
<table class="table">
    <thead>
        <tr>
            <th>Nama Barang</th>
            <th>Harga Barang</th>
            <th>Deskripsi</th>
        </tr>
    </thead>
    <tbody id="table-body">
        {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
        <!-- {% for barang in list_barang %}
            <tr>
                <th>{{barang.nama_barang}}</th>
                <th>{{barang.harga_barang}}</th>
                <th>{{barang.deskripsi}}</th>
            </tr>
        {% endfor %} -->
    </tbody>
</table>

<form id="form" method="POST" action="{% url 'wishlist:post_wishlist' %}">
    {% csrf_token %}
    <table>
        <tr>
            <td>Nama Barang:</td>
            <td><input type="text" name="nama_barang" class="form-control" /></td>
        </tr>
        <tr>
            <td>Harga Barang:</td>
            <td><input type="number" name="harga_barang" class="form-control" /></td>
        </tr>
        <tr>
            <td>Deskripsi:</td>
            <td><textarea name="deskripsi"></textarea></td>
        </tr>
        <tr>
            <td></td>
            <td><input class="btn" type="submit" value="Submit"></td>
        </tr>
    </table>
    
    
    
</form>

<h5>Sesi terakhir login: {{ last_login }}</h5>

<button><a href="{% url 'wishlist:logout' %}">Logout</a></button>

{% endblock content %}